aws_region = "ap-southeast-1"
namespace = "jiyeon-ptfe"
aws_instance_ami = "ami-0dad20bd1b9c8c004"
aws_instance_type = "m5.large"
ssh_key_name = "jiyeon-key"
owner = "dbrown"
ttl = "-1"
multi_availability_zone = "true"
